import { CarouselContent2_2$127 } from "./CarouselContent2_2$127";
import { Button_1$48 } from "./Button_1$48";
import { CarouselContent1_2$44 } from "./CarouselContent1_2$44";
import React, { FC, CSSProperties } from "react";
export const Home_1$4: FC<{
  style: CSSProperties,
}> = (props) => {
  return (
    <div
      data-fid="1:4"
      style={{
        ...{
          display: "flex",
          flexDirection: "column",
          paddingBottom: 64,
          gap: 64,
          justifyContent: "center",
          position: "absolute",
          boxSizing: "border-box",
          backgroundColor: "#ffffff",
        },
        ...props.style,
      }}
      data-fname="Home"
    >
      <div
        data-fid="2:22"
        style={{
          zIndex: 0,
          position: "relative",
          boxSizing: "border-box",
          flexGrow: 0,
          alignSelf: "stretch",
          height: 768,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage:
            "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
          backgroundSize: "cover",
        }}
        data-fname="TopTop"
      >
        <div
          data-fid="1:5"
          style={{
            zIndex: 1,
            position: "absolute",
            boxSizing: "border-box",
            top: 0,
            height: 44,
            left: 0,
            right: 0,
            backgroundColor: "#000000",
          }}
          data-fname="Toolbar"
        >
          <div
            data-fid="1:12"
            style={{
              zIndex: 0,
              position: "absolute",
              boxSizing: "border-box",
              top: "52%",
              transform: " translateY(-50%)",
              height: 13,
              right: 28,
              width: 51,
              color: "#ffffff",
              fontSize: 10.800000190734863,
              fontWeight: 400,
              fontFamily: '"Roboto"',
              fontStyle: "normal",
              lineHeight: "125%",
              letterSpacing: "0px",
              textAlign: "right",
            }}
            data-fname="your name"
          >
            <span style={{}} key="end">
              your name
            </span>
          </div>
          <div
            data-fid="47:30"
            style={{
              zIndex: 1,
              display: "flex",
              flexDirection: "row",
              gap: 2,
              position: "absolute",
              boxSizing: "border-box",
              top: "52%",
              transform: " translateY(-50%) translateX(-50%)",
              height: 13,
              left: "49%",
              width: 201,
              backgroundColor: "rgba(0, 0, 0, 0)",
            }}
            data-fname="Frame 17"
          >
            <div
              data-fid="50:30"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 11,
                height: 11,
                color: "#ffffff",
                fontSize: 10.800000190734863,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Sign in"
            >
              <span style={{}} key="end">
                👻
              </span>
            </div>
            <div
              data-fid="1:14"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 181,
                height: 13,
                color: "#ffffff",
                fontSize: 10.800000190734863,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Sign in"
            >
              <span style={{}} key="end">
                This example site is generated by figg
              </span>
            </div>
            <div
              data-fid="47:31"
              style={{
                zIndex: 2,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 5,
                height: 13,
                color: "#ffffff",
                fontSize: 10.800000190734863,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Sign in"
            >
              <span style={{}} key="end">
                🥳
              </span>
            </div>
          </div>
        </div>
        <div
          data-fid="1:28"
          style={{
            zIndex: 0,
            position: "absolute",
            boxSizing: "border-box",
            top: 44,
            height: 108,
            left: 0,
            right: 0,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="Frame 2"
        >
          <div
            data-fid="33:42"
            style={{
              zIndex: 2,
              position: "absolute",
              boxSizing: "border-box",
              top: 43,
              height: 19.636362075805664,
              left: 40,
              width: 18,
              backgroundColor: "#000000",
              opacity: 0,
            }}
            data-fname="shopping-bag"
          >
            <div
              data-fid="33:43"
              style={{
                zIndex: 0,
                position: "absolute",
                boxSizing: "border-box",
                height: "100%",
                top: "0%",
                width: "100%",
                left: "0%",
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="18" height="20" viewBox="0 0 18 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.1429 6.13636V4.90909C14.1429 2.20219 11.8358 0 9 0C6.1642 0 3.85714 2.20219 3.85714 4.90909V6.13636H0V16.5682C0 18.2627 1.43908 19.6364 3.21429 19.6364H14.7857C16.5609 19.6364 18 18.2627 18 16.5682V6.13636H14.1429ZM6.42857 4.90909C6.42857 3.55564 7.5821 2.45455 9 2.45455C10.4179 2.45455 11.5714 3.55564 11.5714 4.90909V6.13636H6.42857V4.90909ZM12.8571 9.51136C12.3246 9.51136 11.8929 9.09927 11.8929 8.59091C11.8929 8.08255 12.3246 7.67045 12.8571 7.67045C13.3897 7.67045 13.8214 8.08255 13.8214 8.59091C13.8214 9.09927 13.3897 9.51136 12.8571 9.51136ZM5.14286 9.51136C4.61029 9.51136 4.17857 9.09927 4.17857 8.59091C4.17857 8.08255 4.61029 7.67045 5.14286 7.67045C5.67542 7.67045 6.10714 8.08255 6.10714 8.59091C6.10714 9.09927 5.67542 9.51136 5.14286 9.51136Z" fill="white"/>
</svg>
`,
                }}
              />
            </div>
          </div>
          <div
            data-fid="47:32"
            style={{
              zIndex: 1,
              display: "flex",
              flexDirection: "row",
              gap: 4,
              position: "absolute",
              boxSizing: "border-box",
              top: 45,
              height: 17,
              left: "48%",
              transform: " translateX(-50%)",
              width: 116,
              backgroundColor: "rgba(0, 0, 0, 0)",
            }}
            data-fname="Frame 18"
          >
            <div
              data-fid="47:41"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 7,
                height: 17,
                color: "#ffffff",
                fontSize: 14.399999618530273,
                fontWeight: 700,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="🧼"
            >
              <span style={{}} key="end">
                🧼
              </span>
            </div>
            <div
              data-fid="1:30"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 86,
                height: 17,
                color: "#ffffff",
                fontSize: 14.399999618530273,
                fontWeight: 700,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Coming soon"
            >
              <span style={{}} key="end">
                Coming soon
              </span>
            </div>
            <div
              data-fid="47:33"
              style={{
                zIndex: 2,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 15,
                height: 14,
                color: "#ffffff",
                fontSize: 14.399999618530273,
                fontWeight: 700,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="👺"
            >
              <span style={{}} key="end">
                👺
              </span>
            </div>
          </div>
          <div
            data-fid="1:34"
            style={{
              zIndex: 0,
              display: "flex",
              flexDirection: "row",
              gap: 32,
              alignItems: "center",
              position: "absolute",
              boxSizing: "border-box",
              top: "49%",
              transform: " translateY(-50%)",
              height: 18.002967834472656,
              right: 40,
              width: 68,
              backgroundColor: "rgba(0, 0, 0, 0)",
            }}
            data-fname="Frame 3"
          >
            <div
              data-fid="33:41"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 18,
                height: 18.002967834472656,
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.7552 15.5647L14.2499 12.0594C14.0917 11.9012 13.8772 11.8133 13.6522 11.8133H13.0791C14.0495 10.5722 14.6261 9.01115 14.6261 7.31299C14.6261 3.27327 11.3528 0 7.31303 0C3.27329 0 0 3.27327 0 7.31299C0 11.3527 3.27329 14.626 7.31303 14.626C9.01121 14.626 10.5723 14.0494 11.8134 13.079V13.6521C11.8134 13.8771 11.9013 14.0916 12.0595 14.2498L15.5648 17.7551C15.8953 18.0856 16.4297 18.0856 16.7567 17.7551L17.7517 16.7601C18.0822 16.4296 18.0822 15.8952 17.7552 15.5647ZM7.31303 11.8133C4.82731 11.8133 2.81271 9.80222 2.81271 7.31299C2.81271 4.82728 4.82379 2.81269 7.31303 2.81269C9.79876 2.81269 11.8134 4.82376 11.8134 7.31299C11.8134 9.79871 9.80228 11.8133 7.31303 11.8133Z" fill="white"/>
</svg>
`,
                }}
              />
            </div>
            <div
              data-fid="33:39"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 18,
                height: 15.034090042114258,
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0.642857 2.76136H17.3571C17.7122 2.76136 18 2.48665 18 2.14773V0.613636C18 0.274717 17.7122 0 17.3571 0H0.642857C0.287799 0 0 0.274717 0 0.613636V2.14773C0 2.48665 0.287799 2.76136 0.642857 2.76136ZM0.642857 8.89773H17.3571C17.7122 8.89773 18 8.62301 18 8.28409V6.75C18 6.41108 17.7122 6.13636 17.3571 6.13636H0.642857C0.287799 6.13636 0 6.41108 0 6.75V8.28409C0 8.62301 0.287799 8.89773 0.642857 8.89773ZM0.642857 15.0341H17.3571C17.7122 15.0341 18 14.7594 18 14.4205V12.8864C18 12.5474 17.7122 12.2727 17.3571 12.2727H0.642857C0.287799 12.2727 0 12.5474 0 12.8864V14.4205C0 14.7594 0.287799 15.0341 0.642857 15.0341Z" fill="white"/>
</svg>
`,
                }}
              />
            </div>
          </div>
        </div>
        <div
          data-fid="1:44"
          style={{
            zIndex: 2,
            display: "flex",
            flexDirection: "column",
            gap: 20,
            alignItems: "center",
            position: "absolute",
            boxSizing: "border-box",
            top: "56%",
            transform: " translateY(-50%) translateX(-50%)",
            height: 382.6690979003906,
            left: "50%",
            width: 371,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="header-text"
        >
          <div
            data-fid="2:20"
            style={{
              zIndex: 0,
              display: "flex",
              flexDirection: "column",
              gap: 4,
              alignItems: "center",
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 289,
              height: 308,
              backgroundColor: "rgba(0, 0, 0, 0)",
            }}
            data-fname="Frame 6"
          >
            <div
              data-fid="2:21"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 80,
                height: 44,
              }}
              data-fname="Rectangle 1"
            ></div>
            <div
              data-fid="1:42"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 112,
                height: 76,
                color: "#ffffff",
                fontSize: 57,
                fontWeight: 500,
                fontFamily: '"Futura"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Figg"
            >
              <span style={{}} key="end">
                Figg
              </span>
            </div>
            <div
              data-fid="1:43"
              style={{
                zIndex: 2,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 289,
                height: 180,
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "213.3333396911621%",
                letterSpacing: "0px",
                textAlign: "justify",
              }}
              data-fname="Figg is another “Figma to React” platform, designed to be AST-based code generation of multiple template language and keep the output up-to-date"
            >
              <span style={{}} key="end">
                Figg is another “Figma to React” platform, designed to be
                AST-based code generation of multiple template language and keep
                the output up-to-date
              </span>
            </div>
          </div>
          <div
            data-fid="47:35"
            style={{
              zIndex: 1,
              display: "flex",
              flexDirection: "row",
              paddingTop: 16,
              paddingRight: 32,
              paddingBottom: 16,
              paddingLeft: 32,
              gap: 2,
              justifyContent: "center",
              alignItems: "center",
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 371,
              height: 54.669097900390625,
              backgroundColor: "#ffffff",
              borderRadius: "68px 68px 68px 68px",
            }}
            data-fname="Button"
          >
            <div
              data-fid="47:37"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 18,
                height: 18,
                color: "#000000",
                fontSize: 18,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="🐝"
            >
              <span style={{}} key="end">
                🐝
              </span>
            </div>
            <div
              data-fid="47:36"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 263,
                height: 17,
                color: "#000000",
                fontSize: 14.399999618530273,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="asdfa sdfasdf"
            >
              <span style={{}} key="end">
                Coming soon (go to GitHub project page)
              </span>
            </div>
            <div
              data-fid="47:40"
              style={{
                zIndex: 2,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 22,
                height: 22.669099807739258,
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="22" height="23" viewBox="0 0 22 23" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7.35847 18.2531C7.35847 18.3469 7.25645 18.4219 7.12782 18.4219C6.98145 18.4359 6.87944 18.3609 6.87944 18.2531C6.87944 18.1594 6.98145 18.0844 7.11008 18.0844C7.24314 18.0703 7.35847 18.1453 7.35847 18.2531ZM5.97903 18.0422C5.94798 18.1359 6.03669 18.2437 6.16976 18.2719C6.28508 18.3187 6.41815 18.2719 6.44476 18.1781C6.47137 18.0844 6.3871 17.9766 6.25403 17.9344C6.13871 17.9016 6.01008 17.9484 5.97903 18.0422ZM7.93952 17.9625C7.81089 17.9953 7.72218 18.0844 7.73548 18.1922C7.74879 18.2859 7.86411 18.3469 7.99718 18.3141C8.12581 18.2812 8.21452 18.1922 8.20121 18.0984C8.1879 18.0094 8.06814 17.9484 7.93952 17.9625ZM10.8581 0C4.70605 0 0 4.93594 0 11.4375C0 16.6359 3.09597 21.0844 7.51815 22.65C8.08589 22.7578 8.28548 22.3875 8.28548 22.0828C8.28548 21.7922 8.27218 20.1891 8.27218 19.2047C8.27218 19.2047 5.16734 19.9078 4.51532 17.8078C4.51532 17.8078 4.00968 16.4437 3.28226 16.0922C3.28226 16.0922 2.26653 15.3562 3.35323 15.3703C3.35323 15.3703 4.45766 15.4641 5.06532 16.5797C6.03669 18.3891 7.66452 17.8687 8.29879 17.5594C8.40081 16.8094 8.68911 16.2891 9.00847 15.9797C6.52903 15.6891 4.02742 15.3094 4.02742 10.8C4.02742 9.51094 4.36452 8.86406 5.07419 8.03906C4.95887 7.73438 4.58185 6.47812 5.18952 4.85625C6.11653 4.55156 8.25 6.12188 8.25 6.12188C9.1371 5.85938 10.0907 5.72344 11.0355 5.72344C11.9802 5.72344 12.9339 5.85938 13.821 6.12188C13.821 6.12188 15.9544 4.54688 16.8815 4.85625C17.4891 6.48281 17.1121 7.73438 16.9968 8.03906C17.7065 8.86875 18.1411 9.51562 18.1411 10.8C18.1411 15.3234 15.5286 15.6844 13.0492 15.9797C13.4573 16.35 13.8032 17.0531 13.8032 18.1547C13.8032 19.7344 13.7899 21.6891 13.7899 22.0734C13.7899 22.3781 13.994 22.7484 14.5573 22.6406C18.9927 21.0844 22 16.6359 22 11.4375C22 4.93594 17.0101 0 10.8581 0ZM4.31129 16.1672C4.25363 16.2141 4.26694 16.3219 4.34234 16.4109C4.41331 16.4859 4.51532 16.5188 4.57298 16.4578C4.63064 16.4109 4.61734 16.3031 4.54194 16.2141C4.47097 16.1391 4.36895 16.1062 4.31129 16.1672ZM3.83226 15.7875C3.80121 15.8484 3.84556 15.9234 3.93427 15.9703C4.00524 16.0172 4.09395 16.0031 4.125 15.9375C4.15605 15.8766 4.11169 15.8016 4.02298 15.7547C3.93427 15.7266 3.86331 15.7406 3.83226 15.7875ZM5.26935 17.4562C5.19839 17.5172 5.225 17.6578 5.32702 17.7469C5.42903 17.8547 5.55766 17.8687 5.61532 17.7938C5.67298 17.7328 5.64637 17.5922 5.55766 17.5031C5.46008 17.3953 5.32702 17.3813 5.26935 17.4562ZM4.76371 16.7672C4.69274 16.8141 4.69274 16.9359 4.76371 17.0438C4.83468 17.1516 4.95444 17.1984 5.0121 17.1516C5.08306 17.0906 5.08306 16.9688 5.0121 16.8609C4.95 16.7531 4.83468 16.7063 4.76371 16.7672Z" fill="black"/>
</svg>
`,
                }}
              />
            </div>
          </div>
        </div>
        <div
          data-fid="33:47"
          style={{
            zIndex: 4,
            position: "absolute",
            boxSizing: "border-box",
            height: "1.171875%",
            top: "92.1875%",
            left: "50%",
            transform: " translateX(-50%)",
            width: 14,
          }}
          data-fname="Vector"
        >
          <div
            className="vector"
            dangerouslySetInnerHTML={{
              __html: `<svg preserveAspectRatio="none" width="14" height="9" viewBox="0 0 14 9" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.26039 8.69288L0.308534 2.76839C-0.102845 2.35891 -0.102845 1.69676 0.308534 1.29163L1.29759 0.307115C1.70897 -0.102372 2.37418 -0.102372 2.78118 0.307115L7 4.50654L11.2188 0.307115C11.6302 -0.102372 12.2954 -0.102372 12.7024 0.307115L13.6915 1.29163C14.1028 1.70111 14.1028 2.36326 13.6915 2.76839L7.73961 8.69288C7.33698 9.10237 6.67177 9.10237 6.26039 8.69288Z" fill="white"/>
</svg>
`,
            }}
          />
        </div>
        <div className="maxer">
          <div
            data-fid="2:6"
            style={{
              zIndex: 3,
              position: "absolute",
              boxSizing: "border-box",
              bottom: 40,
              height: 31,
              right: 61,
              width: 31,
              backgroundColor: "#ffffff",
              borderRadius: "61px 61px 61px 61px",
            }}
            data-fname="Frame 5"
          >
            <div
              data-fid="33:45"
              style={{
                zIndex: 0,
                position: "absolute",
                boxSizing: "border-box",
                height: "18.38994026184082%",
                top: "41.935483870967744%",
                width: "58.064516129032256%",
                left: "22.580645161290324%",
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="18" height="6" viewBox="0 0 18 6" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.6129 2.85044C11.6129 4.4261 10.4444 5.70088 9 5.70088C7.55564 5.70088 6.3871 4.4261 6.3871 2.85044C6.3871 1.27478 7.55564 0 9 0C10.4444 0 11.6129 1.27478 11.6129 2.85044ZM15.3871 0C13.9427 0 12.7742 1.27478 12.7742 2.85044C12.7742 4.4261 13.9427 5.70088 15.3871 5.70088C16.8315 5.70088 18 4.4261 18 2.85044C18 1.27478 16.8315 0 15.3871 0ZM2.6129 0C1.16855 0 0 1.27478 0 2.85044C0 4.4261 1.16855 5.70088 2.6129 5.70088C4.05726 5.70088 5.22581 4.4261 5.22581 2.85044C5.22581 1.27478 4.05726 0 2.6129 0Z" fill="black"/>
</svg>
`,
                }}
              />
            </div>
          </div>
        </div>
      </div>
      <div
        data-fid="2:35"
        style={{
          zIndex: 1,
          position: "relative",
          boxSizing: "border-box",
          flexGrow: 0,
          alignSelf: "stretch",
          height: 300,
          backgroundColor: "rgba(0, 0, 0, 0)",
        }}
        data-fname="carousel"
      >
        <div
          data-fid="2:28"
          style={{
            zIndex: 0,
            display: "flex",
            flexDirection: "row",
            gap: 20,
            alignItems: "center",
            position: "absolute",
            boxSizing: "border-box",
            top: 0,
            height: 300,
            left: 72,
            width: 1260,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="Frame 9"
        >
          <CarouselContent1_2$44
            data-fid="2:45"
            style={{
              zIndex: 0,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 300,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="carousel content 1"
          ></CarouselContent1_2$44>
          <CarouselContent1_2$44
            data-fid="2:47"
            style={{
              zIndex: 1,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 300,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 11"
          ></CarouselContent1_2$44>
          <CarouselContent1_2$44
            data-fid="2:49"
            style={{
              zIndex: 2,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 300,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 12"
          ></CarouselContent1_2$44>
          <CarouselContent1_2$44
            data-fid="2:51"
            style={{
              zIndex: 3,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 300,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 13"
          ></CarouselContent1_2$44>
        </div>
        <div
          data-fid="2:36"
          style={{
            zIndex: 1,
            position: "absolute",
            boxSizing: "border-box",
            top: "50%",
            transform: " translateY(-50%)",
            height: 51,
            right: 36,
            width: 51,
            backgroundColor: "#ffffff",
            boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
            borderRadius: "61px 61px 61px 61px",
          }}
          data-fname="Frame 6"
        >
          <div
            data-fid="33:49"
            style={{
              zIndex: 0,
              position: "absolute",
              boxSizing: "border-box",
              height: "27.45098039215686%",
              top: "37.254901960784316%",
              width: "17.647058823529413%",
              left: "41.1764705882353%",
            }}
            data-fname="Vector"
          >
            <div
              className="vector"
              dangerouslySetInnerHTML={{
                __html: `<svg preserveAspectRatio="none" width="9" height="14" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8.69341 7.74352L2.76856 13.6917C2.35905 14.1028 1.69686 14.1028 1.2917 13.6917L0.307134 12.7032C-0.102378 12.2921 -0.102378 11.6273 0.307134 11.2206L4.50681 7.00437L0.307134 2.78819C-0.102378 2.37707 -0.102378 1.71228 0.307134 1.30553L1.28735 0.308341C1.69686 -0.10278 2.35905 -0.10278 2.7642 0.308341L8.68905 6.25648C9.10292 6.6676 9.10292 7.3324 8.69341 7.74352Z" fill="black"/>
</svg>
`,
              }}
            />
          </div>
        </div>
      </div>
      <div
        data-fid="2:55"
        style={{
          zIndex: 2,
          position: "relative",
          boxSizing: "border-box",
          flexGrow: 0,
          alignSelf: "stretch",
          height: 768,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage:
            "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
          backgroundSize: "cover",
        }}
        data-fname="Second section"
      >
        <div
          data-fid="2:65"
          style={{
            zIndex: 0,
            display: "flex",
            flexDirection: "column",
            gap: 20,
            position: "absolute",
            boxSizing: "border-box",
            top: 157,
            height: 284,
            left: 72,
            width: 289,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="Frame 4"
        >
          <div
            data-fid="2:66"
            style={{
              zIndex: 0,
              display: "flex",
              flexDirection: "column",
              gap: 4,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 289,
              height: 215,
              backgroundColor: "rgba(0, 0, 0, 0)",
            }}
            data-fname="Frame 6"
          >
            <div
              data-fid="2:68"
              style={{
                zIndex: 0,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 191,
                height: 67,
                color: "#ffffff",
                fontSize: 57,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "125%",
                letterSpacing: "0px",
                textAlign: "center",
              }}
              data-fname="Sample"
            >
              <span style={{}} key="end">
                Sample
              </span>
            </div>
            <div
              data-fid="2:69"
              style={{
                zIndex: 1,
                position: "relative",
                boxSizing: "border-box",
                flexGrow: 0,
                alignSelf: "inherit",
                width: 289,
                height: 144,
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 400,
                fontFamily: '"Roboto"',
                fontStyle: "normal",
                lineHeight: "213.3333396911621%",
                letterSpacing: "0px",
                textAlign: "justify",
              }}
              data-fname="asdfasdf asd fasd fasdf asdf asdf aasdf asd fasd fasdf asdfasdf asdf asdfa sdfasd f asdfasdf"
            >
              <span style={{}} key="23">
                asdfasdf asd fasd fasdf
              </span>
              <br key="br23" />
              <span style={{}} key="end">
                asdf asdf aasdf asd fasd fasdf asdfasdf asdf asdfa sdfasd f
                asdfasdf
              </span>
            </div>
          </div>
          <Button_1$48
            data-fid="2:70"
            style={{
              zIndex: 1,
              display: "flex",
              flexDirection: "row",
              paddingTop: 16,
              paddingRight: 32,
              paddingBottom: 16,
              paddingLeft: 32,
              alignItems: "center",
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 153,
              height: 49,
              backgroundColor: "#ffffff",
              borderRadius: "68px 68px 68px 68px",
            }}
            data-fname="Button"
          ></Button_1$48>
        </div>
        <div className="maxer">
          <div
            data-fid="2:71"
            style={{
              zIndex: 1,
              position: "absolute",
              boxSizing: "border-box",
              bottom: 40,
              height: 31,
              right: 61,
              width: 31,
              backgroundColor: "#ffffff",
              borderRadius: "61px 61px 61px 61px",
            }}
            data-fname="Frame 5"
          >
            <div
              data-fid="33:52"
              style={{
                zIndex: 0,
                position: "absolute",
                boxSizing: "border-box",
                height: "18.38994026184082%",
                top: "41.935483870967744%",
                width: "58.064516129032256%",
                left: "22.580645161290324%",
              }}
              data-fname="Vector"
            >
              <div
                className="vector"
                dangerouslySetInnerHTML={{
                  __html: `<svg preserveAspectRatio="none" width="18" height="6" viewBox="0 0 18 6" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.6129 2.85044C11.6129 4.4261 10.4444 5.70088 9 5.70088C7.55564 5.70088 6.3871 4.4261 6.3871 2.85044C6.3871 1.27478 7.55564 0 9 0C10.4444 0 11.6129 1.27478 11.6129 2.85044ZM15.3871 0C13.9427 0 12.7742 1.27478 12.7742 2.85044C12.7742 4.4261 13.9427 5.70088 15.3871 5.70088C16.8315 5.70088 18 4.4261 18 2.85044C18 1.27478 16.8315 0 15.3871 0ZM2.6129 0C1.16855 0 0 1.27478 0 2.85044C0 4.4261 1.16855 5.70088 2.6129 5.70088C4.05726 5.70088 5.22581 4.4261 5.22581 2.85044C5.22581 1.27478 4.05726 0 2.6129 0Z" fill="black"/>
</svg>
`,
                }}
              />
            </div>
          </div>
        </div>
      </div>
      <div
        data-fid="18:0"
        style={{
          zIndex: 3,
          position: "relative",
          boxSizing: "border-box",
          flexGrow: 0,
          alignSelf: "stretch",
          height: 119,
          backgroundColor: "rgba(0, 0, 0, 0)",
        }}
        data-fname="Frame 16"
      >
        <div
          data-fid="2:88"
          style={{
            zIndex: 0,
            display: "flex",
            flexDirection: "column",
            paddingLeft: 32,
            justifyContent: "center",
            position: "absolute",
            boxSizing: "border-box",
            top: 0,
            height: 103,
            left: 0,
            width: 321,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="Frame 14"
        >
          <div
            data-fid="2:86"
            style={{
              zIndex: 0,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 191,
              height: 67,
              color: "#000000",
              fontSize: 57,
              fontWeight: 400,
              fontFamily: '"Roboto"',
              fontStyle: "normal",
              lineHeight: "125%",
              letterSpacing: "0px",
              textAlign: "center",
            }}
            data-fname="Sample"
          >
            <span style={{}} key="end">
              Sample
            </span>
          </div>
          <div
            data-fid="2:87"
            style={{
              zIndex: 1,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 289,
              height: 36,
              color: "#000000",
              fontSize: 18,
              fontWeight: 400,
              fontFamily: '"Roboto"',
              fontStyle: "normal",
              lineHeight: "213.3333396911621%",
              letterSpacing: "0px",
              textAlign: "justify",
            }}
            data-fname="asdfasdf asd fasd fasdf"
          >
            <span style={{}} key="end">
              asdfasdf asd fasd fasdf
            </span>
          </div>
        </div>
      </div>
      <div
        data-fid="2:89"
        style={{
          zIndex: 4,
          position: "relative",
          boxSizing: "border-box",
          flexGrow: 0,
          alignSelf: "stretch",
          height: 382,
          backgroundColor: "rgba(0, 0, 0, 0)",
        }}
        data-fname="carousel"
      >
        <div
          data-fid="2:90"
          style={{
            zIndex: 0,
            display: "flex",
            flexDirection: "row",
            gap: 20,
            position: "absolute",
            boxSizing: "border-box",
            top: 0,
            bottom: 0,
            minHeight: 382,
            left: 72,
            width: 1260,
            backgroundColor: "rgba(0, 0, 0, 0)",
          }}
          data-fname="Frame 9"
        >
          <CarouselContent2_2$127
            data-fid="2:128"
            style={{
              zIndex: 0,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 382,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 8"
          ></CarouselContent2_2$127>
          <CarouselContent2_2$127
            data-fid="2:134"
            style={{
              zIndex: 1,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 382,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 9"
          ></CarouselContent2_2$127>
          <CarouselContent2_2$127
            data-fid="2:140"
            style={{
              zIndex: 2,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 382,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 10"
          ></CarouselContent2_2$127>
          <CarouselContent2_2$127
            data-fid="2:146"
            style={{
              zIndex: 3,
              position: "relative",
              boxSizing: "border-box",
              flexGrow: 0,
              alignSelf: "inherit",
              width: 300,
              height: 382,
              backgroundColor: "rgba(0, 0, 0, 0)",
              backgroundImage:
                "url(https://s3-alpha-sig.figma.com/img/bc1a/04d9/6e40f86b35e43b1121d9c766114cb456?Expires=1621209600&Signature=AO1Khjh~89aPV-miKwbEjUH4Ne2lPuaTxkdXaKmXz~MZ-OfWZKHNZ9~qGpWLM2FC1yCJTMn4lFwu4xFP42-nsR6QvQfF1EYG9ebg-7UytgaP1O-~fxa3c6GBy9H0lYW260jIoO5KsbJyYyhRUT6D1Xuwh2saDom-mSELRdC-WR4YEtYO8FcchJO5MzsK8d8Vjxg8tIz0DPWAC1QKdz58Ygd5BxQnbF5v86ihqyPKjkB63FAHm-DJ0egUyHCC9eFpHbVwFYmtrBufwyj89yZ1WqcZIq-Dzr~Mt0hv-4OIB7~CC-xyEy-svRZfYf2bwgU1Nt7n7rWnyM-FLYqeZ3s0fw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA)",
              backgroundSize: "cover",
              borderRadius: "6.75px 6.75px 6.75px 6.75px",
            }}
            data-fname="Frame 11"
          ></CarouselContent2_2$127>
        </div>
        <div
          data-fid="2:95"
          style={{
            zIndex: 1,
            position: "absolute",
            boxSizing: "border-box",
            top: "50%",
            transform: " translateY(-50%)",
            height: 51,
            right: 36,
            width: 51,
            backgroundColor: "#ffffff",
            boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
            borderRadius: "61px 61px 61px 61px",
          }}
          data-fname="Frame 6"
        >
          <div
            data-fid="33:50"
            style={{
              zIndex: 0,
              position: "absolute",
              boxSizing: "border-box",
              height: "27.45098039215686%",
              top: "37.254901960784316%",
              width: "17.647058823529413%",
              left: "41.1764705882353%",
            }}
            data-fname="Vector"
          >
            <div
              className="vector"
              dangerouslySetInnerHTML={{
                __html: `<svg preserveAspectRatio="none" width="9" height="14" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8.69341 7.74352L2.76856 13.6917C2.35905 14.1028 1.69686 14.1028 1.2917 13.6917L0.307134 12.7032C-0.102378 12.2921 -0.102378 11.6273 0.307134 11.2206L4.50681 7.00437L0.307134 2.78819C-0.102378 2.37707 -0.102378 1.71228 0.307134 1.30553L1.28735 0.308341C1.69686 -0.10278 2.35905 -0.10278 2.7642 0.308341L8.68905 6.25648C9.10292 6.6676 9.10292 7.3324 8.69341 7.74352Z" fill="black"/>
</svg>
`,
              }}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
